// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htztsnekcqtjlaxmjwfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0enRzbmVrY3F0amxheG1qd2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTkyNjUsImV4cCI6MjA2NTg3NTI2NX0.cBkWI07rr4WexBka5AbWJBvxjhSzEdoECGeJ9ShxOd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);